---
repos:
  - repo: local
    hooks:
      - id: uv-install
        name: poetry-install
        description: install Poetry dependencies from the lock file
        entry: uv sync
        language: python
        pass_filenames: false
        stages: [post-checkout, post-merge]
        always_run: true
      - id: ruff-lint
        name: ruff-lint
        entry: uv run ruff check
        args:
          [
            --force-exclude,
            --config,
            pyproject.toml,
            --fix,
            --show-fixes,
            --exit-non-zero-on-fix,
          ]
        language: system
        types_or: [python]
        require_serial: true # run once for all files
      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format
        args: [--force-exclude, --config, pyproject.toml]
        language: system
        types_or: [python]
        require_serial: true # run once for all files
